name: 'Gist as CDN'
description: 'Upload artifacts to a github gist'
inputs:
  FILES:  # id of input
    description: 'Glob of file(s) to upload'
    required: true
  GIST:
    description: "Where to upload files"
    required: true
runs:
  using: 'node16'
  steps:
    - name: "list files"
      run: ls
      shell: bash