name: 'Gist as CDN'
description: 'Upload artifacts to a github gist'
inputs:
  FILES:  # id of input
    description: 'What to upload'
    required: true
  GIST:
    description: "Where to upload files"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'