name: Dogfooding this action
on:
  push:
    branches: [ master, testing ]

jobs:
  build:
    permissions: write-all
    name: dogfood
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Run
        uses: ./
        with:
          FILES: "*.md"
          GIST: "a75f4dcf3202a129802100332335019a"
          TOKEN: ${{ secrets.GITHUB_TOKEN }}