name: Dogfooding this action
on:
  push:
    branches: [ master, testing ]

jobs:
  build:
    name: dogfood
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Run
        uses: ./
        with:
          FILES: "README.md" # we'll use this repo's README as an example
          GIST: "a75f4dcf3202a129802100332335019a"